---
title: "Table"
author: "Yujie Zhao"
date: "2023-02-09"
output: html_document
---

```{r}
# load libraries
rm(list=ls())
library(gtsummary)
library(dplyr)

```


```{r}
# load data
dat = read.csv("./Analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)
```


# by patient 
```{r}
dat_patient = as.data.frame(dat[,colnames(dat) %in% c("patient_rename","Age_IO","Tumor","Sex","clinical.response","IO.enrollment")])

patient_sample = NULL
for (i in unique(dat_patient$patient_rename)){
  tmp = dat_patient[dat_patient$patient_rename == i,]
  n = nrow(tmp)
  tmp = data.frame(distinct(tmp))
  tmp[7] = n
  patient_sample = rbind(patient_sample, tmp)
  
}

colnames(patient_sample) = c(colnames(patient_sample)[-length(colnames(patient_sample))],"Number.of.samples")
patient_sample$Number.of.samples = as.numeric(patient_sample$Number.of.samples)
patient_sample = patient_sample %>% mutate(IO.drug = case_when(
  IO.enrollment == "Cemiplimab" ~ "Cemiplimab(anti-PD1/PDL1)",
  IO.enrollment == "Pembrolizumab" ~ "Pembrolizumab(anti-PD1/PDL1)",
  IO.enrollment == "Nivolumab" ~ "Nivolumab(anti-PD1/PDL1)",
  IO.enrollment == "Avelumab" ~ "Avelumab(anti-PD1/PDL1)",
  IO.enrollment == "Nivolumab + Ipilimumab" ~ "Nivolumab(anti-PD1/PDL1)+Ipilimumab(anti-CTLA4)"
))
patient_sample$IO.drug = factor(patient_sample$IO.drug,
                                           levels= c("Cemiplimab(anti-PD1/PDL1)","Pembrolizumab(anti-PD1/PDL1)",
"Nivolumab(anti-PD1/PDL1)" ,"Avelumab(anti-PD1/PDL1)", "Nivolumab(anti-PD1/PDL1)+Ipilimumab(anti-CTLA4)"))

patient_sample = patient_sample %>% mutate(Response = case_when(
  clinical.response == "Responder" ~ "Responder/R",
  clinical.response == "Stable_Disease" ~ "Stable_Disease/SD",
  clinical.response == "Nonresponder" ~ "Nonresponder/NR",
  clinical.response == "Other" ~ "Other (radiotherapy, organ transplant, unevaluable)",
))



patient_sample$Response = factor(patient_sample$Response,levels = c("Responder/R","Nonresponder/NR",
       "Stable_Disease/SD","Other (radiotherapy, organ transplant, unevaluable)"))


tbl.gts <- patient_sample %>%
  # categorical variables must be factors or character strings
  # apply the tbl_summary() function
  tbl_summary(
    by = Tumor, # Treatment variable
    label = list(
      Age_IO ~ "Age [yrs] (sd)",
      Sex ~ "Sex (%)",
      IO.drug ~ "Treatment (%)",
      Response ~ "ICI Response (%)",
      Number.of.samples ~ "Total Fecal Samples"
    ),
    type = c(Age_IO,Number.of.samples) ~ "continuous",
    statistic = list(Age_IO ~ "{mean} ({sd})",Number.of.samples~"{sum}"),
    # may be also ...
    # statistic = list(all_continuous() ~ "{median} ({p25}, {p75})"),
    digits = all_continuous() ~ 0,
    missing_text = "(Missing)",
    include = c("Age_IO","Sex","Tumor","IO.drug","Response","Number.of.samples"))%>%
  as_gt() %>%
  gt::gtsave(filename ="./Analysis/cohort_summary.docx")

```








