---
title: "Microbiome Sequence data Differential_analysis"
author: "Yujie Zhao"
date: "2023-02-14"
output: html_document
---

```{r}
rm(list=ls())
library(ggplot2)
library(vegan)
library(permute)
library(lattice)
library(plyr)
library(getopt)
library(ggfortify)
library(ade4)
library(ggpubr)

library(pheatmap)
library(cowplot)
library(stringr)


color=c("#A94643","#3E4A7B","#BCBDB8")

```

# first_sample

```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv")

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.benefit,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)
rownames(group)=group$sample_id
first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = first_sample[first_sample$days.sample.collect < 180,]



```



# wilcox

```{r}
level = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")
level_name = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")

tumor = list(c("BCC","SCC","MCC"),"SCC")
tumor_name = c("3_tumor","SCC")

for (x in 1:length(level)){
  for (j in 1:length(tumor)){

dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",level[x],".txt"),sep="\t",row.names = 1,check.names = F)
data=as.data.frame(dat[,10:ncol(dat)])
data=data[,which(colSums(data)>0.01)]

first_sample_tumor = first_sample[first_sample$Tumor %in% tumor[[j]],]
first_sample_tumor =first_sample_tumor[order(match(first_sample_tumor$clinical.response,c("Responder","Nonresponder"))),]
data=data[rownames(first_sample_tumor),]


group_name= unique(first_sample_tumor$clinical.response)
sample = rownames(first_sample_tumor[first_sample_tumor$clinical.response %in% c(group_name[1],group_name[2]),])
sample_len = nrow(first_sample_tumor[first_sample_tumor$clinical.response  %in% group_name[1],])

a = t(data[sample,])
Pvalue<-c(rep(0,nrow(a)))
log2_FC<-c(rep(0,nrow(a)))


for(i in 1:nrow(a)){
  if(sd(a[i,1:sample_len])==0&&sd(a[i,(sample_len+1):ncol(a)])==0){
    Pvalue[i] <-"NA"
    log2_FC[i]<-"NA"
  }else{
    y=wilcox.test(as.numeric(a[i,1:sample_len]),
                    as.numeric(a[i,(sample_len+1):ncol(a)])) 
    Pvalue[i]<-y$p.value
    log2_FC[i]<-log2((mean(as.numeric(a[i,1:sample_len]))+0.000001)/(mean(as.numeric(a[i,(sample_len+1):ncol(a)]))+0.000001))
    }
  }

fdr=p.adjust(Pvalue,"BH")
out<-data.frame(v1=rownames(a),log2_FC,Pvalue,fdr)
out = na.omit(out)
out$log2_FC = as.numeric(out$log2_FC)


if (file.exists(paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/"))){
} else {
    dir.create(file.path(paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/")))
}

if (file.exists(paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/",level_name[x],"/"))){
} else {
    dir.create(file.path(paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/",level_name[x],"/")))
}

write.table(out,paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/",level_name[x],"/wilcox.txt"),sep="\t",row.names = FALSE)

  }
  }


tumor
```


# lefse-input
```{r}
level = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")
level_name = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")
tumor = list(c("BCC","SCC","MCC"),"SCC")
tumor_name = c("3_tumor","SCC")

for (x in 1:length(level)){
  for (j in 1:length(tumor)){

    dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",level[x],".txt"),sep="\t",row.names = 1,check.names = F)
    data=as.data.frame(dat[,10:ncol(dat)])
    data=data[,which(colSums(data)>0.01)]
    
    first_sample_tumor = first_sample[first_sample$Tumor %in% tumor[[j]],]
    first_sample_tumor =first_sample_tumor[order(match(first_sample_tumor$clinical.response,c("Responder","Nonresponder"))),]
    data=data[rownames(first_sample_tumor),]
    
    
    data = data.frame(cbind(response =first_sample_tumor$clinical.response,
                            sample =  unlist(first_sample_tumor$sample_id),data))
    
    colnames(data)=gsub("\\.","__",colnames(data))
    
    data=data.frame(t(data))
    
    if (file.exists(paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/"))){
    } else {
        dir.create(file.path(paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/")))
    }
    
    if (file.exists(paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/",level_name[x],"/"))){
    } else {
        dir.create(file.path(paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/",level_name[x],"/")))
    }
    
    write.table(data,paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/",level_name[x],"/input_lefse.txt"),sep="\t",quote=F,col.names = FALSE)


  }
  }


```


# lefse 
lefse_format_input.py example.txt example.in -c 1 -u 2 -o 1000000
lefse_run.py example.in example.res -a 0.1 -w 0.1

# combined 
```{r}

level = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")
level_name = c("species","genus","class","family","order","phylum","picrust","picrust2.ec","picrust2.ko","picrust2.pw")
tumor = list(c("BCC","SCC","MCC"),"SCC")
tumor_name = c("3_tumor","SCC")


for (x in 1:length(level)){
  for (j in 1:length(tumor)){


    lefse = read.csv(paste0("../analysis/differential_analysis/lefse/",tumor_name[j],"/",level_name[x],"/lefse.res"),sep="\t",header = F,row.names = 1)
    colnames(lefse)=c("v1","response","LDA","p_value")
    rownames(lefse)= gsub("__","\\.",rownames(lefse))
    
    out = read.csv(paste0("../analysis/differential_analysis/wilcox/",tumor_name[j],"/",level_name[x],"/wilcox.txt"),sep="\t",row.names = 1,check.names = F,header = T)
    new=as.data.frame(merge(lefse,out,by="row.names",all=TRUE))
    rownames(new) = new$Row.names
    
    
    if (file.exists(paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/"))){
    } else {
        dir.create(file.path(paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/")))
    }
    
    if (file.exists(paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/",level_name[x],"/"))){
    } else {
        dir.create(file.path(paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/",level_name[x],"/")))
    }
    
    write.table(new,paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/",level_name[x],"/differential.txt"),sep="\t",quote=F,row.names = FALSE)
    
    new_select = na.omit(new)
    write.table(new_select,paste0("../analysis/differential_analysis/combined/",tumor_name[j],"/",level_name[x],"/differential_select.txt"),sep="\t",quote=F,row.names = FALSE)
    
  }
  }
```



```{r}
library("stringr")
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])

first_sample = first_sample[first_sample$Tumor == "SCC",]
squamous = group[group$Tumor == "SCC",]

dat=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.genus.txt",sep="\t",row.names = 1,check.names = F)
differential = read.csv("../analysis/differential_analysis/combined/SCC/genus/differential.txt",sep="\t",row.names = 1,check.names = F)
differential = na.omit(differential)

dat = dat[,rownames(differential)]

first_sample = first_sample[order(first_sample$patient_rename),]
first_sample = first_sample[order(match(first_sample$clinical.response,c("Responder","Nonresponder"))),]
dat = dat[rownames(first_sample),]
rownames(dat) = first_sample$patient_rename


diff = read.csv("../analysis/differential_analysis/combined/SCC/species/differential.txt",sep = "\t")
diff = na.omit(diff)
diff=diff[!startsWith(diff$Row.names, "otu"),]

species = read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.species.txt",sep="\t",row.names = 1)
species=species[,10:ncol(species)]
species=species[rownames(first_sample),]
rownames(species) = first_sample$patient_rename
species = species[,diff$Row.names]


dat = data.frame(cbind(species,dat))


write.csv(t(dat),"../analysis/differential_analysis/combined/SCC/differential_genus_species.csv",col.names = NA)
```



