---
title: "Fig_1"
author: "Yujie Zhao"
date: "2023-02-07"
output: html_document
---
# Microbial Composition by Tumor Type

Fig1A. Swimmer plot depicting metadata for the cohort
F1g1B: top 20 abundance table of genus level
Fig1C: Alpha diversity

# libraries
```{r}
rm(list=ls())
library(ggplot2)
library(vegan)
library(permute)
library(lattice)
library(plyr)
library(getopt)
library(ggfortify)
library(ade4)
library(ggpubr)
library(swimplot)
library(dplyr)
library(openxlsx)
library(reshape2)
library(stringr)
```


# select sample less than 18- days
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv")

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = first_sample[first_sample$days.sample.collect < 180,]

```

#fig1A
```{r}

dat = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv")
dat=as.data.frame(dat)


a = dat[order(match(dat$clinical.response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
a = a[order(match(a$Tumor,rev(unique(a$Tumor)))),]
a$clinical.response = factor(a$clinical.response,levels=c("Responder","Nonresponder","Stable_Disease","Other"))

arm_plot <- swimmer_plot(df=a,id='patient_rename',end='days.io.end',name_fill='clinical.response',col=NA,width=.5,id_order = rev(unique(a$patient_rename)))+labs(x='Patient')

# event, sample collection, progression, death, toxicity 
sample_coll = as.data.frame(cbind(patient_rename = group$patient_rename, days.sample = as.numeric(group$days.sample.collect)))
sample_coll$group = "A"
sample_coll$event = "stool_sample_collection"
sample_coll=unique(sample_coll)

progression =as.data.frame(cbind(patient_rename = dat$patient_rename, days.sample = as.numeric(dat$days.PFS),group = dat$progression.vs.censor))
progression$event = "Progression"
progression=unique(progression)

death =as.data.frame(cbind(patient_rename = dat$patient_rename, days.sample = as.numeric(dat$days.OS),group = dat$death.vs.censor))
death$event = "Death"
death=unique(death)
death1 = death[death$group == "death",]
death2 =  death[death$group == "censor",]
death2$group = "censor_death"
point_data = rbind(progression,death1,sample_coll,death2)
point_data$days.sample = as.numeric(point_data$days.sample)

death2$days.sample = as.numeric(death2$days.sample)
death2$continue.alive = 1


death_line =as.data.frame(cbind(patient_rename = dat$patient_rename, days.ioend = as.numeric(dat$days.io.end),days.sample = as.numeric(dat$days.OS),group = dat$death.vs.censor))
death_line=unique(death_line)
death_line$days.ioend = as.numeric(death_line$days.ioend)
death_line$days.sample = as.numeric(death_line$days.sample)

arm_plot2 = arm_plot +
  scale_fill_manual(name='clinical.response',values=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B","Stable_Disease"="#79ADD6","Other"="grey"))+
  swimmer_lines(df_lines=death_line,id="patient_rename",start =
"days.ioend",end="days.sample",size=0.5,col="#11723E",linetype="dotdash")+
  swimmer_points(df_points= point_data,id='patient_rename',time='days.sample',name_shape =
 'group',name_size = 'group',name_col = 'group',alpha=0.9)+ scale_shape_manual(name="group",values=c(19,0,2,17,15))+scale_colour_manual(name='group',values=c("A" = "black", "progression"="red","censor"='red',"death"="#11723E","censor_death" ="#11723E"))+scale_size_manual(name='group',values=c("A" = 3, "progression"=4,"censor"=4,"death"=4,"censor_death" =4))+
  scale_y_continuous(name = "Time since enrollment (days)")+theme_bw()+
  guides(fill = guide_legend(override.aes = list(shape = NA),title="ICI Response"))+ 
  theme(text = element_text(size=14),axis.text = element_text(size=14,colour="black"),strip.text.x = element_text(size = 14),legend.text = element_text(size=14), axis.title.x =element_text(size=14),axis.text.x =element_text(size=14),
        axis.text.y =element_text(size=12),axis.title.y =element_text(size=14),legend.position = "right")+
  annotate("text", x=20.45, y=3500, label="Alive",size=4)+
  annotate("text",x=20, y=3500, label=sprintf('\u2192'),size=9,col="#11723E")+coord_flip(clip = 'off', ylim = c(0, 3000))

```

#figB
```{r}
color=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B","Stable_Disease"="#79ADD6","Other"="grey")
###########################
dat=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.genus.txt",sep="\t",row.names = 1,check.names = F)
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F,row.names =1)
dat=dat[rownames(group),]
data=as.data.frame(dat[,10:ncol(dat)])
#########################################
GroupCols = c("#eb3eab", "#FF9AA2", "#FFDAC1", "#E2F0CB", "#B5EAD7", "#C7CEEA", "#8e7cc3", "#f94144","#f8961e","#f9b14a","#f9c74f","#90be6d","#82d3d1","#4d908e","#6ec2e5","#277da1","#8DD3C7", "#FFFFB3", "#BEBADA","#e4e4e4")

numTx     = 19
A = cbind(Patient=group$patient_rename,response=group$clinical.response,days = as.numeric(group$days.sample.collect),tumor=group$Tumor,data)#[,-ncol(data)]
# calculate mean for each patient by each genus
##### aggA            = aggregate( .~ RecordID + response, data=A, FUN=mean)
cmaggA          = colMeans(A[5:ncol(A)])
selectedA       = names(cmaggA[order(cmaggA, decreasing=TRUE)])[1:19]
aggA            = A[,c("Patient", "response","days","tumor", selectedA)]
aggA$Other.taxa = 100-rowSums(aggA[5:ncol(aggA)])
aggA$sample = rownames(aggA)


meltA           = melt(aggA, id.vars = c("Patient", "response","days","sample","tumor"))
colnames(meltA) = c("Patient", "response","days","sample","Tumor", "Taxa", "Abundance")

meltA$Patient    = factor(meltA$Patient)
meltA$sample    = factor(meltA$sample,levels=rownames(group))
meltA$days = factor(meltA$days)

meltA$Patient  = factor(meltA$Patient,levels=unique(group$patient_rename))
meltA$Taxa = gsub("k_Bacteria.p_Firmicutes.c_Clostridia.o_Clostridiales.f_unassigned.g_unassigned",
                  "o_Clostridiales.f_unassigned",meltA$Taxa)
meltA$Taxa = gsub("k_Bacteria.p_unassigned.c_unassigned.o_unassigned.f_unassigned.g_unassigned",
                  "k_Bacteria.p_unassigned",meltA$Taxa)
meltA$Taxa = gsub("k_Bacteria.p_Firmicutes.c_Bacilli.o_unassigned.f_unassigned.g_unassigned",
                  "c_Bacilli.o_unassigned",meltA$Taxa)

meltA$Taxa = str_replace(meltA$Taxa, "k_.*.f_", "")
meltA$Taxa      = factor(meltA$Taxa, levels=rev(unique(meltA$Taxa)))

names(GroupCols) = unique(meltA$Taxa)

colnames(meltA) = c("Patient","response","days","sample","Tumor","Genus" ,"Abundance")
##################################

meltA_basal = meltA[meltA$Tumor == "BCC",]

bcc_abundan = meltA_basal %>%
	group_by(Genus) %>%
	summarise(mean_run = sum(Abundance))
bcc_abundan = bcc_abundan[order(bcc_abundan$mean_run, decreasing=TRUE),]

meltA_basal = meltA_basal[order(match(meltA_basal$response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
meltA_basal$Patient = factor(meltA_basal$Patient,levels = unique(meltA_basal$Patient))
p1 <- ggplot(meltA_basal, aes(x=days, y=Abundance, fill=Genus)) +
  geom_bar(position="stack", stat="identity", colour="white", size=0.25) +
  theme_bw() +ggtitle("BCC")+
  scale_fill_manual(values=GroupCols) +
  theme(axis.text.x = element_text(size=8,angle=90, hjust=0.5, vjust=0.5,colour="black"),
        axis.text = element_text(size=14, colour="black"),
        axis.title.y =element_text(size=14),
        panel.grid.major = element_blank(),plot.title = element_text(size=14,hjust = 0.5,vjust=0),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        strip.text.x = element_text(size = 8, angle = 90)) +
  xlab(" ") +
  ylab("% Abundance") +
  facet_grid(~Patient, space="free_x", scale="free_x") 

info=meltA_basal[,c("Patient","response")]
info=unique(info)
length = c(nrow(info[info$response == unique(info$response)[1],]),
           nrow(info[info$response == unique(info$response)[2],]),
           nrow(info[info$response == unique(info$response)[3],]))


g <- ggplot_gtable(ggplot_build(p1))
strips <- which(grepl('strip-', g$layout$name))
#"#A94643","#3E4A7B",
pal= c(rep("#A94643",length[1]),rep("#3E4A7B",length[2]),rep("#79ADD6",length[3]))

for (i in seq_along(strips)) {
  k <- which(grepl('rect', g$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  l <- which(grepl('titleGrob', g$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  g$grobs[[strips[i]]]$grobs[[1]]$children[[k]]$gp$fill <- pal[i]
  g$grobs[[strips[i]]]$grobs[[1]]$children[[l]]$children[[1]]$gp$col <- "white"}

###############################################
meltA_basal = meltA[meltA$Tumor == "MCC",]
bcc_abundan = meltA_basal %>%
	group_by(Genus) %>%
	summarise(mean_run = sum(Abundance))
bcc_abundan = bcc_abundan[order(bcc_abundan$mean_run, decreasing=TRUE),]
meltA_basal = meltA_basal[order(match(meltA_basal$response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
meltA_basal$Patient = factor(meltA_basal$Patient,levels = unique(meltA_basal$Patient))
p1 <- ggplot(meltA_basal, aes(x=days, y=Abundance, fill=Genus)) +
  geom_bar(position="stack", stat="identity", colour="white", size=0.25) +
  theme_bw() +ggtitle("MCC")+
  scale_fill_manual(values=GroupCols) +
  theme(axis.text.x = element_text(size=8,angle=90, hjust=0.5, vjust=0.5, colour="black"),
        panel.grid.major = element_blank(),plot.title = element_text(size=14,hjust = 0.5,vjust=0),
        panel.grid.minor = element_blank(),
         axis.text.y = element_blank(),axis.ticks.y = element_blank(),
        legend.position = "none",
        strip.text.x = element_text(size = 8, angle = 90)) +
  xlab("Days From ICI Start ------->") +ylab(NULL)+
  facet_grid(~Patient, space="free_x", scale="free_x") 

info=meltA_basal[,c("Patient","response")]
info=unique(info)
length = c(nrow(info[info$response == unique(info$response)[1],]),
           nrow(info[info$response == unique(info$response)[2],]),
           nrow(info[info$response == unique(info$response)[3],]))

g2 <- ggplot_gtable(ggplot_build(p1))
strips <- which(grepl('strip-', g2$layout$name))
color=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B","SD"="#79ADD6","Other"="grey")
pal= c(rep("#A94643",length[1]),rep("#3E4A7B",length[2]),rep("grey",length[3]))

for (i in seq_along(strips)) {
  k <- which(grepl('rect', g2$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  l <- which(grepl('titleGrob', g2$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  g2$grobs[[strips[i]]]$grobs[[1]]$children[[k]]$gp$fill <- pal[i]
  g2$grobs[[strips[i]]]$grobs[[1]]$children[[l]]$children[[1]]$gp$col <- "white"}

##########################
meltA_basal = meltA[meltA$Tumor == "SCC",]
bcc_abundan = meltA_basal %>%
	group_by(Genus) %>%
	summarise(mean_run = sum(Abundance))
bcc_abundan = bcc_abundan[order(bcc_abundan$mean_run, decreasing=TRUE),]
meltA_basal = meltA_basal[order(match(meltA_basal$response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
meltA_basal$Patient = factor(meltA_basal$Patient,levels = unique(meltA_basal$Patient))
p1 <- ggplot(meltA_basal, aes(x=days, y=Abundance, fill=Genus)) +
  geom_bar(position="stack", stat="identity", colour="white", size=0.25, colour="black") +
  theme_bw() +ggtitle("SCC")+
  scale_fill_manual(values=GroupCols) +
  theme(axis.text.x = element_text(size=8,angle=90, hjust=0.5, vjust=0.5, colour="black"),
        axis.text.y = element_blank(),axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),plot.title = element_text(size=14,hjust = 0.5,vjust=0),
        panel.grid.minor = element_blank(),legend.text = element_text(size=12),legend.title = element_text(size=12),
        strip.text.x = element_text(size = 8, angle = 90)) +guides(fill=guide_legend(ncol =1))+
  xlab(" ") +ylab(NULL)+
  facet_grid(~Patient, space="free_x", scale="free_x") 

info=meltA_basal[,c("Patient","response")]
info=unique(info)
length = c(nrow(info[info$response == unique(info$response)[1],]),
           nrow(info[info$response == unique(info$response)[2],]),
           nrow(info[info$response == unique(info$response)[3],]))

g3 <- ggplot_gtable(ggplot_build(p1))
strips <- which(grepl('strip-', g3$layout$name))
pal= c(rep("#A94643",length[1]),rep("#3E4A7B",length[2]),rep("grey",length[3]))

for (i in seq_along(strips)) {
  k <- which(grepl('rect', g3$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  l <- which(grepl('titleGrob', g3$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
  g3$grobs[[strips[i]]]$grobs[[1]]$children[[k]]$gp$fill <- pal[i]
  g3$grobs[[strips[i]]]$grobs[[1]]$children[[l]]$children[[1]]$gp$col <- "white"}


```

# C alpha-diversity-treatment
```{r}
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group$time_group = NA
for (i in 1:nrow(group)){
  if (group[i,"days.sample.collect"] < 180){
     group[i,"time_group"] = "<180 days"
  }
  else if (group[i,"days.sample.collect"] >=180 & group[i,"days.sample.collect"]< 360){
     group[i,"time_group"] = "180-360 days"
  }
  else if (group[i,"days.sample.collect"] >= 360){
     group[i,"time_group"] = ">=360 days"
  }}

color2 = c("#FC8002","#4995C6","#369F2D") 
alpha_diversity=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.alpha-diversity.txt",sep="\t",row.names = 1,check.names = F)
clinical_benefit_group = group[group$clinical.response == "Responder",]
alpha_diversity=alpha_diversity[rownames(clinical_benefit_group),]

alpha_diversity$Treatment_Duration = factor(clinical_benefit_group$time_group,levels=c("<180 days","180-360 days",">=360 days"))
alpha_diversity$ICI_response = factor(clinical_benefit_group$clinical.response)
format = theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      axis.title = element_text(size=12,colour="black"),plot.title = element_text(size = 12),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.ticks.x = element_blank(),legend.position = "none",
        axis.text.x = element_blank())
p1 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = shannon,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
  #geom_point(position = position_jitter(0.1),aes(shape=ICI_response))scale_shape_manual(values = c(19,1))+
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$shannon),max(alpha_diversity$shannon)*1.3))+ 
  theme_bw()+xlab("")+ggtitle("Shannon Index")+ylab("")+format
  

p2 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = simpson_reciprocal,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$simpson_reciprocal),max(alpha_diversity$simpson_reciprocal)*1.3))+ 
  theme_bw()+xlab("")+ggtitle("Simpson_reciprocal")+ylab("")+format
#ggsave(p2,file="./squamous/baseline_alpha_diversity_simpson_reciprocal.pdf", width=4, height=3.5)


p3 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = chao1,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$chao1),max(alpha_diversity$chao1)*1.3))+ 
  theme_bw()+xlab("")+ggtitle("Chao1")+ylab("")+format
#ggsave(p3,file="./squamous/baseline_alpha_diversity_chao1.pdf", width=4, height=3.5)



p4 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = observed_species,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$observed_species),max(alpha_diversity$observed_species)*1.3))+ 
  theme_bw()+xlab("")+ggtitle("Observed_species")+ylab("")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.title =element_text(size=12,colour="black"),plot.title = element_text(size = 12),
      axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
      legend.text = element_text(size=12),
      legend.title = element_text(size=12))


combined_plot = ggarrange(    p1,p2, p3,p4,
          ncol = 4,widths  = c(0.45, 0.5, 0.55,0.85))
          #labels = "A"                                        # Labels of the scatter plot


#ggsave(combined_plot,file=paste0("./alpha_diversity/Fig2_A.pdf"), width=12, height=3.5)


```


# Fig1
```{r}
combined = ggarrange(arm_plot2,
          ggarrange(g,g2,g3, nrow = 1,ncol =3,widths=c(1,1,2.5)),
          combined_plot,
          #ggarrange(pc1,pc2,pc3,pc,nrow = 1,ncol =4,labels=c("C","","","D"),widths=c(1,1,1,1)),
          nrow = 3,ncol =1,labels=c("A","B","C"),heights = c(1,1.3,1))

ggsave(combined,file="../analysis/Graph/fig1.pdf", width=15, height=15)

```






