---
title: "Fig3_scc_first_sample"
author: "Yujie Zhao"
date: "2023-03-28"
output: html_document
---

```{r}

rm(list=ls())
library(ggplot2)
library(vegan)
library(permute)
library(lattice)
library(plyr)
library(getopt)
library(ggfortify)
library(ade4)
library(ggpubr)
library(pheatmap)
library(cowplot)
library(reshape2)
color=c("#A94643","#3E4A7B","#BCBDB8")

```


# data cleanup and rearrange
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)
group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])


first_sample = first_sample[first_sample$Tumor == "SCC",]
squamous = group[group$Tumor == "SCC",]

squamous$time_group = NA

for (i in 1:nrow(squamous)){
  if (squamous[i,"days.sample.collect"] < 180){
     squamous[i,"time_group"] = "<180 days"
  }
  else if (squamous[i,"days.sample.collect"] >=180 & squamous[i,"days.sample.collect"]< 360){
     squamous[i,"time_group"] = "180-360 days"
  }
  else if (squamous[i,"days.sample.collect"] >= 360){
     squamous[i,"time_group"] = ">=360 days"
  }}

```



# A SCC alpha diversity
```{r}
color2 = c("#FC8002","#4995C6","#369F2D") 
alpha_diversity=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.alpha-diversity.txt",sep="\t",row.names = 1,check.names = F)
res_squamous = squamous[squamous$clinical.response == "Responder",]
alpha_diversity=alpha_diversity[rownames(res_squamous),]
alpha_diversity$Treatment_Duration = factor(res_squamous$time_group,levels=c("<180 days","180-360 days",">=360 days"))
alpha_diversity$ICI_response = factor(res_squamous$clinical.response,c( "Responder","Nonresponder"))

format = theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      axis.title = element_text(size=12,colour="black"),plot.title = element_text(size = 12),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.ticks.x = element_blank(),legend.position = "none",
        axis.text.x = element_blank())

p1 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = shannon,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$shannon),max(alpha_diversity$shannon)*1.3))+ 
  theme_bw()+ggtitle("Shannon Index")+theme(axis.title.x = element_blank())+format+ylab("")

p2 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = simpson_reciprocal,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$simpson_reciprocal),max(alpha_diversity$simpson_reciprocal)*1.3))+ 
  theme_bw()+ggtitle("Simpson_reciprocal")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format
#ggsave(p2,file="./squamous/baseline_alpha_diversity_simpson_reciprocal.pdf", width=4, height=3.5)


p3 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = chao1,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4,show.legend = FALSE) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$chao1),max(alpha_diversity$chao1)*1.3))+ 
  theme_bw()+ggtitle("Chao1")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format
#ggsave(p3,file="./squamous/baseline_alpha_diversity_chao1.pdf", width=4, height=3.5)



p4 = ggplot(alpha_diversity, aes(x =Treatment_Duration, y = observed_species,fill=Treatment_Duration))+scale_fill_manual(values=color2)+ 
  geom_boxplot(width=0.4) + 
geom_point(position = position_jitter(0.1))+
  stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("<180 days","180-360 days"),c("<180 days",">=360 days"),c(">=360 days","180-360 days")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$observed_species),max(alpha_diversity$observed_species)*1.3))+ 
  theme_bw()+ggtitle("Observed_species")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),plot.title = element_text(size = 12),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.title =element_text(size=12,colour="black"),
      axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
      legend.text = element_text(size=12),
      legend.title = element_text(size=12))

          #labels = "A"                                        # Labels of the scatter plot




```


# B lefse heatmap + species 
```{r}

dat = read.csv("../analysis/differential_analysis/combined/SCC/differential_genus_species.csv",row.names = 1)
dat = as.data.frame(t(dat))
first_sample = first_sample[order(first_sample$patient_rename),]
first_sample = first_sample[first_sample$clinical.response %in% c("Responder","Nonresponder"),]
first_sample = first_sample[order(match(first_sample$clinical.response,c("Responder","Nonresponder"))),]
dat = dat[first_sample$patient_rename,]
rownames(dat) = first_sample$patient_rename

anncolo_all = list(group = c("Nonresponder"="#3E4A7B","Responder" ="#A94643"))

ann_col=data.frame(group=first_sample$clinical.response)
rownames(ann_col)=rownames(dat)

nrow(ann_col[ann_col$group =="Responder",])

dat=as.data.frame(scale(dat))
bk1 <- c(seq(floor(min(dat)),0,by=0.01))
bk2 <- c(seq(0,ceiling(max(dat)),by=0.01))

pheatmap(t(dat),cellheight = 10,cellwidth = 11,cluster_rows = F,
           annotation_col = ann_col,fontsize = 11,
           annotation_names_row=FALSE,annotation_names_col = FALSE,annotation_legend = TRUE,
         gaps_col = c(nrow(first_sample[first_sample$clinical.response == unique(first_sample$clinical.response)[1],])),
         gaps_row = c(3,3),
           annotation_colors = anncolo_all,
           cluster_cols = F,show_colnames=T,
  	color = c(colorRampPalette(colors = c("navy","SteelBlue","white"))(length(bk1)),
                                              colorRampPalette(colors = c("white","orange","red"))(length(bk2))),
  	)->y

  B<-plot_grid(y$gtable)


```




# C boxplot for individual differential microbiome
```{r}
dat=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.genus.txt",sep="\t",row.names = 1,check.names = F)

alltumor = read.csv("../analysis/differential_analysis/combined/3_tumor/genus/differential_select.txt",sep="\t",row.names = 1,check.names = F)
SCC = read.csv("../analysis/differential_analysis/combined/SCC/genus/differential_select.txt",sep="\t",row.names = 1,check.names = F)
diff = intersect(rownames(alltumor),rownames(SCC))

dat = dat[,diff]
dat = dat[rownames(first_sample),]

rownames(dat) = first_sample$patient_rename
dat$response = first_sample$clinical.response
colnames(dat) = gsub('.*.g_','',colnames(dat))
#plot = melt(dat,id="response")
color = c("Nonresponder"="#3E4A7B","Responder" ="#A94643")
format = theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      plot.title =element_text(size=12,colour="black",hjust = 0.5),
      axis.title = element_text(size=12,colour="black"),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.ticks.x = element_blank(),legend.position = "none",
        axis.text.x = element_blank())

Barnesiella = ggplot(dat, aes(x =response, y =Barnesiella ,fill=response))+
  geom_boxplot(width=0.4) + 
  geom_point(aes(fill=response),shape=21,size=2,alpha=0.8)+scale_fill_manual(values=color)+ scale_colour_manual(values=color)+ 
  #stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(dat$Barnesiella)*0.9,max(dat$Barnesiella)*1.2))+ labs(title="Barnesiella")+
  theme_bw()+xlab("")+ylab("% abundance")+format


Mahella = ggplot(dat, aes(x =response, y =Mahella ,fill=response))+
  geom_boxplot(width=0.4) + 
  geom_point(aes(fill=response),shape=21,size=2,alpha=0.8)+scale_fill_manual(values=color)+ scale_colour_manual(values=color)+ 
  #stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(dat$Mahella)*0.9,max(dat$Mahella)*1.2))+ labs(title="Mahella")+
  theme_bw()+xlab("")+ylab("% abundance")+format+theme(axis.title.y = element_blank())


Hydrogenoanaerobacterium = ggplot(dat, aes(x =response, y =Hydrogenoanaerobacterium ,fill=response))+
  geom_boxplot(width=0.4) + 
  geom_point(aes(fill=response),shape=21,size=2,alpha=0.8)+scale_fill_manual(values=color)+ scale_colour_manual(values=color)+ 
  #stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(dat$Hydrogenoanaerobacterium)*0.9,max(dat$Hydrogenoanaerobacterium)*1.2))+ labs(title="Hydrogenoanaerobacterium")+
  theme_bw()+xlab("")+ylab("% abundance")+format+theme(axis.title.y = element_blank())


Ruminococcus = ggplot(dat, aes(x =response, y =Ruminococcus ,fill=response))+
  geom_boxplot(width=0.4) + 
  geom_point(aes(fill=response),shape=21,size=2,alpha=0.8)+scale_fill_manual(values=color)+ scale_colour_manual(values=color)+ 
  #stat_summary(fun=median,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(dat$Ruminococcus)*0.9,max(dat$Ruminococcus)*1.2))+labs(title="Ruminococcus")+
  theme_bw()+xlab("")+ylab("% abundance")+format+theme(axis.title.y = element_blank())


combine_D = ggarrange(Barnesiella, Mahella ,Hydrogenoanaerobacterium,Ruminococcus,ncol = 2,nrow=2)

```



# combine
```{r}
Fig3 = ggarrange( ggarrange(p1,p2, p3,p4,ncol = 4,widths  = c(1, 1, 1.1,2)),
                  ggarrange(B, combine_D,ncol = 2,widths  = c(1,0.6),labels = c("B","C")),
                   nrow = 2,heights  = c(1,2),labels=c("A",""))


ggsave(Fig3,file="../analysis/Graph/Fig 3.pdf", width=10.5, height=8.5)

```

