---
title: "Supplemental Graph"
author: "Yujie Zhao"
date: "2023-10-26"
output: html_document
---

```{r}
rm(list=ls())
library(ggplot2)
library(vegan)
library(permute)
library(lattice)
library(plyr)
library(getopt)
library(ggfortify)
library(ade4)
library(ggpubr)
library(swimplot)
library(dplyr)
library(reshape2)
library(ggsurvfit)
library(dplyr)
library(survival)
library(gtsummary)
library(tidycmprsk)
library(ggrepel)
library(pheatmap)
library(cowplot)
```

# SFig1 survival analysis
```{r}

group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv")
group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]


cohort = as.data.frame(cbind(patient = group$patient_rename, days.OS=group$days.OS, days.PFS = group$days.PFS,
   progression.vs.censor = group$progression.vs.censor, death.vs.censor=group$death.vs.censor,clinical.response=group$clinical.response))
cohort=unique(cohort)
cohort$days.OS = as.numeric(cohort$days.OS)
cohort$days.PFS = as.numeric(cohort$days.PFS)
cohort$clinical.response = factor(cohort$clinical.response)

cohort = cohort %>% mutate(progressive_status = if_else(progression.vs.censor == "progression", 1,0))
cohort = cohort %>% mutate(survival_status = if_else(death.vs.censor == "death", 1,0))

pdf("../analysis/Graph/survival_analysis.pdf",width = 6,height = 4)
survfit2(Surv(days.OS, survival_status) ~ clinical.response, data = cohort) %>% 
  ggsurvfit() +
  labs(
    x = "Days from ICI Start",
    y = "Overall survival probability"
  ) +scale_color_manual(values=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B"))
dev.off()

summary(coxph(Surv(days.OS, survival_status) ~ clinical.response, data = cohort))


pdf("../analysis/Graph/progression_analysis.pdf",width = 6,height = 4)
survfit2(Surv(days.PFS, progressive_status) ~ clinical.response, data = cohort) %>% 
  ggsurvfit() +
  labs(
    x = "Days from ICI Start",
    y = "Overall progression probability"
  ) +scale_color_manual(values=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B"))
dev.off()

summary(coxph(Surv(days.PFS, progressive_status) ~ clinical.response, data = cohort))


```
# Sfig2 sample distance
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)
group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]
rownames(group) = group$sample_id
group = as.data.frame(group)

dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.genus.txt"),sep="\t",row.names = 1,check.names = F)
dat=as.data.frame(dat[,10:ncol(dat)])
dat=dat[,which(colSums(dat)>0.01)]

cal_sample_distance = function(group,data,value){
  tmp = group[group$clinical.response == value,]
  tmp_dat=dat[rownames(tmp),]
  tab.dist<-vegdist(tmp_dat,method="bray")
  mat = as.matrix(tab.dist)
  mat_long = subset(melt(mat), value!=0)
  for (i in rownames(mat_long)){
    if (tmp[mat_long[i,"Var1"],"patient"] == tmp[mat_long[i,"Var2"],"patient"]){
       mat_long[i,"group"] = "within_patient"
    }else{
      mat_long[i,"group"] = "across_patient"
    }
  }
  
  mat_long$response = value
  return(mat_long) 
}

nonres = cal_sample_distance(group,data,"Nonresponder")
res = cal_sample_distance(group,data,"Responder")
other = cal_sample_distance(group,data,"Other")
sd =  cal_sample_distance(group,data,"Stable_Disease")

mat_long = as.data.frame(rbind(nonres,res,other,sd))
mat_long$group = factor(mat_long$group,level= c("within_patient","across_patient"))
color = c("within_patient"="#ADDB88","across_patient" ="#369F2D")


 a = ggplot(mat_long, aes(x =group, y =value ,fill=group))+
  geom_boxplot(width=0.4) +# geom_point()+
  scale_fill_manual(values=color)+ scale_colour_manual(values=color)+ 
  stat_compare_means(comparisons =list(c("within_patient","across_patient" )),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(mat_long$value)*1,max(mat_long$value)*1.1))+
  theme_bw()+xlab("")+ylab("Distance")+facet_wrap(vars(response))+
theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      plot.title =element_text(size=12,colour="black",hjust = 0.5),
      axis.title = element_text(size=12,colour="black",),axis.text.x = element_blank(),axis.ticks.x = element_blank())
      
ggsave(a,file="../analysis/Graph/SFig2.pdf", width=7, height=6)

```





# SFig3 PCoA
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv")

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])
color=c("Responder" = "#A94643", "Nonresponder"="#3E4A7B","Stable_Disease"="#79ADD6","Other"="grey")
i="genus"
########
dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",i,".txt"),sep="\t",row.names = 1,check.names = F)
    dat=dat[rownames(first_sample),]
    data=as.data.frame(dat[,10:ncol(dat)])
    data=data[,which(colSums(data)>0.01)]
    tab.dist<-vegdist(data,method="bray")
    data$group = first_sample$clinical.response
    set.seed(123)
    data.adonis<- adonis2(tab.dist~group,data,permutations = 999)
    pr = data.adonis$`Pr(>F)`[1]
    pcoa<- dudi.pco(tab.dist, scan = FALSE,nf=10)
    #$eig means how much is each component among 10 components 
    pcoa_eig <- (pcoa$eig)/ sum(pcoa$eig)
    #get 10 components
    plotdata <- data.frame({pcoa$li})
    plotdata$names <- rownames(plotdata)
    #name 10 components
    names(plotdata)[1:3] <- c('PCoA1', 'PCoA2','PCoA3')
    plotdata$response = as.factor(first_sample$clinical.response)
    centroids <- aggregate(cbind(PCoA1,PCoA2)~response, data=plotdata, mean)
    plotdata     <- merge(plotdata,centroids,by="response",suffixes=c("",".centroid"))
    pcall <- ggplot(plotdata, aes(x=PCoA1,y=PCoA2,fill = response)) +
      geom_point(aes(x=PCoA1,y=PCoA2,fill=response,color=response), size=4) +
      geom_point(data=centroids, aes(x=PCoA1,y=PCoA2, fill=response,color=response), pch=21, size=2) +
      geom_segment(aes(x=PCoA1.centroid, y=PCoA2.centroid, xend=PCoA1, yend=PCoA2, color=response), alpha=0.8) +
      scale_fill_manual(values=color) +
      scale_colour_manual(values=color) +
      xlab(paste("PCoA Axis 1 (", round(100 * pcoa_eig[1], 2), "%)", sep="")) +
      ylab(paste("PCoA Axis 2 (", round(100 * pcoa_eig[2], 2), "%)", sep="")) +
      ggtitle(paste0("All Tumor p = ",round(pr,2)," R=",round(data.adonis$R2[2]*100,1),"%"))+
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(), 
            plot.title = element_text(size=14,colour="black"),legend.position = "none",
            axis.text=element_text(size=14,colour="black"),text=element_text(size=14,colour="black"),
            aspect.ratio=1) +
      guides(fill = guide_legend(override.aes=list(shape=21)))
#################################
dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",i,".txt"),sep="\t",row.names = 1,check.names = F)
    first_sample_bcc = first_sample[first_sample$Tumor == "BCC",]
    data=as.data.frame(dat[,10:ncol(dat)])
    data=data[,which(colSums(data)>0.01)]
    data=data[rownames(first_sample_bcc),]
    tab.dist<-vegdist(data,method="bray")
    data$group = first_sample_bcc$clinical.response
    set.seed(123)
    data.adonis<- adonis2(tab.dist~group,data,permutations = 999)
    pr = data.adonis$`Pr(>F)`[1]
    
    pcoa<- dudi.pco(tab.dist, scan = FALSE,nf=10)
    #$eig means how much is each component among 10 components 
    pcoa_eig <- (pcoa$eig)/ sum(pcoa$eig)
    #get 10 components
    plotdata <- data.frame({pcoa$li})
    plotdata$names <- rownames(plotdata)
    #name 10 components
    names(plotdata)[1:3] <- c('PCoA1', 'PCoA2','PCoA3')
    plotdata$response = as.factor(first_sample_bcc$clinical.response)
    centroids <- aggregate(cbind(PCoA1,PCoA2)~response, data=plotdata, mean)
    plotdata     <- merge(plotdata,centroids,by="response",suffixes=c("",".centroid"))
    pc1 <- ggplot(plotdata, aes(x=PCoA1,y=PCoA2,fill = response)) +
      geom_point(aes(x=PCoA1,y=PCoA2,fill=response,color=response), size=4) +
      geom_point(data=centroids, aes(x=PCoA1,y=PCoA2, fill=response,color=response), pch=21, size=2) +
      geom_segment(aes(x=PCoA1.centroid, y=PCoA2.centroid, xend=PCoA1, yend=PCoA2, color=response), alpha=0.8) +
      scale_fill_manual(values=color) +
      scale_colour_manual(values=color) +
      xlab(paste("PCoA Axis 1 (", round(100 * pcoa_eig[1], 2), "%)", sep="")) +
      ylab(paste("PCoA Axis 2 (", round(100 * pcoa_eig[2], 2), "%)", sep="")) +
      ggtitle(paste0("BCC p = ",round(pr,2)," R=",round(data.adonis$R2[2]*100,1),"%"))+
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(), 
            plot.title = element_text(size=14,colour="black"),legend.position = "none",
            axis.text=element_text(size=14,colour="black"),text=element_text(size=14,colour="black"),
            aspect.ratio=1) +
      guides(fill = guide_legend(override.aes=list(shape=21)))
##########################################
dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",i,".txt"),sep="\t",row.names = 1,check.names = F)
    first_sample_mcc = first_sample[first_sample$Tumor == "MCC",]
    data=as.data.frame(dat[,10:ncol(dat)])
    data=data[,which(colSums(data)>0.01)]
    data=data[rownames(first_sample_mcc),]
    tab.dist<-vegdist(data,method="bray")
    data$group = first_sample_mcc$clinical.response
    set.seed(123)
    data.adonis<- adonis2(tab.dist~group,data,permutations = 999)
    pr = data.adonis$`Pr(>F)`[1]
    
    pcoa<- dudi.pco(tab.dist, scan = FALSE,nf=10)
    #$eig means how much is each component among 10 components 
    pcoa_eig <- (pcoa$eig)/ sum(pcoa$eig)
    #get 10 components
    plotdata <- data.frame({pcoa$li})
    plotdata$names <- rownames(plotdata)
    #name 10 components
    names(plotdata)[1:3] <- c('PCoA1', 'PCoA2','PCoA3')
    plotdata$response = as.factor(first_sample_mcc$clinical.response)
    
    centroids <- aggregate(cbind(PCoA1,PCoA2)~response, data=plotdata, mean)
    plotdata     <- merge(plotdata,centroids,by="response",suffixes=c("",".centroid"))

    pc3 <- ggplot(plotdata, aes(x=PCoA1,y=PCoA2,fill = response)) +
      geom_point(aes(x=PCoA1,y=PCoA2,fill=response,color=response), size=4) +
      geom_point(data=centroids, aes(x=PCoA1,y=PCoA2, fill=response,color=response), pch=21, size=2) +
      geom_segment(aes(x=PCoA1.centroid, y=PCoA2.centroid, xend=PCoA1, yend=PCoA2, color=response), alpha=0.8) +
      scale_fill_manual(values=color) +
      scale_colour_manual(values=color) +
      xlab(paste("PCoA Axis 1 (", round(100 * pcoa_eig[1], 2), "%)", sep="")) +
      ylab(paste("PCoA Axis 2 (", round(100 * pcoa_eig[2], 2), "%)", sep="")) +
      ggtitle("MCC")+
      theme_bw() +
      theme(panel.grid.major = element_blank(),legend.position = "none",
            panel.grid.minor = element_blank(),
            plot.title = element_text(size=14,colour="black"),
            axis.text=element_text(size=14,colour="black"),text=element_text(size=14,colour="black"),
            aspect.ratio=1) +
      guides(fill = guide_legend(override.aes=list(shape=21)))
    ##########################################
    dat=read.csv(paste0("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.",i,".txt"),sep="\t",row.names = 1,check.names = F)
    first_sample_scc = first_sample[first_sample$Tumor == "SCC",]
    data=as.data.frame(dat[,10:ncol(dat)])
    data=data[,which(colSums(data)>0.01)]
    data=data[rownames(first_sample_scc),]
    tab.dist<-vegdist(data,method="bray")
    data$group = first_sample_scc$clinical.response
    set.seed(123)
    data.adonis<- adonis2(tab.dist~group,data,permutations = 999)
    pr = data.adonis$`Pr(>F)`[1]
    
    pcoa<- dudi.pco(tab.dist, scan = FALSE,nf=10)
    #$eig means how much is each component among 10 components 
    pcoa_eig <- (pcoa$eig)/ sum(pcoa$eig)
    #get 10 components
    plotdata <- data.frame({pcoa$li})
    plotdata$names <- rownames(plotdata)
    #name 10 components
    names(plotdata)[1:3] <- c('PCoA1', 'PCoA2','PCoA3')
    plotdata$response = as.factor(first_sample_scc$clinical.response)
    
    centroids <- aggregate(cbind(PCoA1,PCoA2)~response, data=plotdata, mean)
    plotdata     <- merge(plotdata,centroids,by="response",suffixes=c("",".centroid"))
    pc2 <- ggplot(plotdata, aes(x=PCoA1,y=PCoA2,fill = response)) +
      geom_point(aes(x=PCoA1,y=PCoA2,fill=response,color=response), size=4) +
      geom_point(data=centroids, aes(x=PCoA1,y=PCoA2, fill=response,color=response), pch=21, size=2) +
      geom_segment(aes(x=PCoA1.centroid, y=PCoA2.centroid, xend=PCoA1, yend=PCoA2, color=response), alpha=0.8) +
      scale_fill_manual(values=color) +
      scale_colour_manual(values=color) +
      xlab(paste("PCoA Axis 1 (", round(100 * pcoa_eig[1], 2), "%)", sep="")) +
      ylab(paste("PCoA Axis 2 (", round(100 * pcoa_eig[2], 2), "%)", sep="")) +
      ggtitle(paste0("SCC p = ",round(pr,2)," R=",round(data.adonis$R2[2]*100,1),"%"))+
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            plot.title = element_text(size=14,colour="black"),
            axis.text=element_text(size=14,colour="black"),text=element_text(size=14,colour="black"),
            aspect.ratio=1) +
      guides(fill = guide_legend(override.aes=list(shape=21)))

supplement = ggarrange(pcall,pc1,pc3,pc2,nrow = 1,ncol =4,widths=c(1,1,1,1.48) )
ggsave(supplement,file="../analysis/Graph/SFig3.pdf", width=15, height=5)

```


# SFig 4 alpha diversity first sample
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)
group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]

ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])


alpha_diversity=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.alpha-diversity.txt",sep="\t",row.names = 1,check.names = F)
alpha_diversity=alpha_diversity[rownames(first_sample),]
alpha_diversity$ICI_response = factor(first_sample$clinical.response,c( "Responder","Nonresponder"))
color = c("Nonresponder"="#3E4A7B","Responder" ="#A94643")

format = theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      axis.title = element_text(size=12,colour="black"),plot.title = element_text(size = 12),
      axis.ticks.x = element_blank(),legend.position = "none",
        axis.text.x = element_blank())

p1 = ggplot(alpha_diversity, aes(x =ICI_response, y = shannon,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(shannon))) + 
geom_point(position = position_jitter(0.1))+
 # stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$shannon),max(alpha_diversity$shannon)*1.1))+ 
  theme_bw()+ggtitle("Shannon Index")+theme(axis.title.x = element_blank())+format+ylab("")

p2 = ggplot(alpha_diversity, aes(x =ICI_response, y = simpson_reciprocal,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(simpson_reciprocal))) + 
geom_point(position = position_jitter(0.1))+
 #  stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
   stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$simpson_reciprocal),max(alpha_diversity$simpson_reciprocal)*1.1))+ 
  theme_bw()+ggtitle("Simpson_reciprocal")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format


p3 = ggplot(alpha_diversity, aes(x =ICI_response, y = chao1,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(chao1))) + 
geom_point(position = position_jitter(0.1))+
  #stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$chao1),max(alpha_diversity$chao1)*1.1))+ 
  theme_bw()+ggtitle("Chao1")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format

p4 = ggplot(alpha_diversity, aes(x =ICI_response, y = observed_species,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,aes(middle = mean(observed_species))) + 
geom_point(position = position_jitter(0.1))+
  #stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
   stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$observed_species),max(alpha_diversity$observed_species)*1.1))+ 
  theme_bw()+ggtitle("Observed_species")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),plot.title = element_text(size = 12),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.title =element_text(size=12,colour="black"),
      axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
      legend.text = element_text(size=12),
      legend.title = element_text(size=12))

fig4A = ggarrange(p1,p2, p3,p4,ncol = 4,widths  = c(1, 1, 1.1,2))

```

```{r}
first_sample=first_sample[first_sample$Tumor == "SCC",]
alpha_diversity=alpha_diversity[rownames(first_sample),]
alpha_diversity$ICI_response = factor(first_sample$clinical.response,c( "Responder","Nonresponder"))
color = c("Nonresponder"="#3E4A7B","Responder" ="#A94643")

format = theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      axis.title = element_text(size=12,colour="black"),plot.title = element_text(size = 12),
      axis.ticks.x = element_blank(),legend.position = "none",
        axis.text.x = element_blank())

p1 = ggplot(alpha_diversity, aes(x =ICI_response, y = shannon,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(shannon))) + 
geom_point(position = position_jitter(0.1))+
 # stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$shannon),max(alpha_diversity$shannon)*1.1))+ 
  theme_bw()+ggtitle("Shannon Index")+theme(axis.title.x = element_blank())+format+ylab("")

p2 = ggplot(alpha_diversity, aes(x =ICI_response, y = simpson_reciprocal,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(simpson_reciprocal))) + 
geom_point(position = position_jitter(0.1))+
 #  stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
   stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$simpson_reciprocal),max(alpha_diversity$simpson_reciprocal)*1.1))+ 
  theme_bw()+ggtitle("Simpson_reciprocal")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format


p3 = ggplot(alpha_diversity, aes(x =ICI_response, y = chao1,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,show.legend = FALSE,aes(middle = mean(chao1))) + 
geom_point(position = position_jitter(0.1))+
  #stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
  stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$chao1),max(alpha_diversity$chao1)*1.1))+ 
  theme_bw()+ggtitle("Chao1")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+format

p4 = ggplot(alpha_diversity, aes(x =ICI_response, y = observed_species,fill=ICI_response))+scale_fill_manual(values=color)+ 
  geom_boxplot(width=0.4,aes(middle = mean(observed_species))) + 
geom_point(position = position_jitter(0.1))+
  #stat_summary(fun=mean,geom='crossbar',size=0.6,width=0.2)+
   stat_compare_means(comparisons =list(c("Responder","Nonresponder")),method = 'wilcox.test',size=4)+
  coord_cartesian(ylim = c(min(alpha_diversity$observed_species),max(alpha_diversity$observed_species)*1.1))+ 
  theme_bw()+ggtitle("Observed_species")+theme(axis.title.x = element_blank(),axis.title.y = element_blank())+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),plot.title = element_text(size = 12),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      #axis.text.x = element_text(angle = 90, hjust = 1),
      axis.title =element_text(size=12,colour="black"),
      axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
      legend.text = element_text(size=12),
      legend.title = element_text(size=12))

fig4B = ggarrange(p1,p2, p3,p4,ncol = 4,widths  = c(1, 1, 1.1,2))
```

```{r}
Fig4 = ggarrange( fig4A,fig4B,
                   nrow = 2,labels=c("A","B"))

ggsave(Fig4,file="../analysis/Graph/SFig4.pdf", width=9, height=6)
```


# SFig5
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder","Stable_Disease","Other"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]
ID = unique(group$patient_rename)
rownames(group)=group$sample_id
first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}
first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])
first_sample = first_sample[first_sample$Tumor == "SCC",]
# wilcox test for species
dat = read.csv("../analysis/differential_analysis/combined/SCC/differential_genus_species.csv",row.names = 1)
dat = as.data.frame(t(dat))
first_sample = first_sample[order(first_sample$patient_rename),]
first_sample = first_sample[first_sample$clinical.response %in% c("Responder","Nonresponder"),]
first_sample = first_sample[order(match(first_sample$clinical.response,c("Responder","Nonresponder"))),]
dat = dat[first_sample$patient_rename,]

Pvalue<-c(rep(0,ncol(dat)))
log2_FC<-c(rep(0,ncol(dat)))
  for(i in 1:ncol(dat)){
    if(sd(dat[first_sample$clinical.response=="Responder",i])==0&&sd(dat[first_sample$clinical.response=="Nonresponder",i])==0){
      Pvalue[i] <-"NA"
      log2_FC[i]<-"NA"
    }else{
      y=wilcox.test(as.numeric(dat[first_sample$clinical.response=="Responder",i]),
                    as.numeric(dat[first_sample$clinical.response=="Nonresponder",i])) 
      Pvalue[i]<-y$p.value
      log2_FC[i]<-log2((mean(as.numeric(dat[first_sample$clinical.response=="Responder",i]))+0.000001)/(mean(as.numeric(dat[first_sample$clinical.response=="Nonresponder",i]))+0.000001))
    }
  }
  fdr=p.adjust(Pvalue,"BH")
  out<-data.frame(v1=colnames(dat),log2_FC,Pvalue,fdr)

  out = out[out$Pvalue < 0.1,]
  
dat = dat[,out$v1]
dat$response = factor(first_sample$clinical.response,levels = c("Responder","Nonresponder"))
plot = melt(dat)
plot$response = factor(plot$response,levels = c("Responder","Nonresponder"))

a = ggplot(plot, aes(x =response, y =value ,fill=response))+
  geom_boxplot(width=0.4) +# geom_point()+
  scale_fill_manual(values=c("Nonresponder"="#3E4A7B","Responder" ="#A94643"))+ scale_colour_manual(values=c("Nonresponder"="#3E4A7B","Responder" ="#A94643"))+ 
  # statistical analysis
  stat_compare_means(comparisons =list(c("Nonresponder","Responder")),method = 'wilcox.test',size=4)+
  theme_bw()+xlab("")+ylab("")+
  facet_wrap(~variable, scales = "free",ncol =5)+
theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      plot.title =element_text(size=12,colour="black",hjust = 0.5),
      axis.title = element_text(size=12,colour="black",),axis.text.x = element_blank(),axis.ticks.x = element_blank())

ggsave(a,file="../analysis/Graph/SFig5.pdf", width=14, height=8)


```


# SFig 6  PCA for metabolites
```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group = group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]


ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])
first_sample = first_sample[first_sample$Tumor == "SCC",]
first_sample = first_sample[rownames(first_sample)[rownames(first_sample)!="F0100"],]
metabolite = read.csv("../analysis/A01.1-add-meta/metabolomics.txt",sep="\t")
rownames(metabolite) = metabolite$ionTopName
metabolite_data = metabolite[,rownames(first_sample)]
meta_rowmean =rowMeans(metabolite_data)
meta_name = names(meta_rowmean[order(meta_rowmean, decreasing=TRUE)])[1:(nrow(metabolite_data)*0.9)]
# sum(rowSums(metabolite_data > 0) > 0.25*nrow(first_sample))
#meta_name = names(meta_rowmean[meta_rowmean > 5000]) #957
metabolite_data = as.data.frame(metabolite_data[meta_name,])
metabolite_data = as.data.frame(t(metabolite_data))
library(psych)
pc <- prcomp(metabolite_data,scale. = TRUE)
plot = data.frame(pc$x)
plot$response = factor(first_sample$clinical.response,levels=c("Responder","Nonresponder"))
color = c("Nonresponder"="#3E4A7B","Responder" ="#A94643")

centroids <- aggregate(cbind(PC1,PC2)~response, data=plot, mean)
plotdata     <- merge(plot,centroids,by="response",suffixes=c("",".centroid"))
pc1 <- ggplot(plotdata, aes(x=PC1,y=PC2,fill = response)) +
      geom_point(aes(x=PC1,y=PC2,fill=response,color=response), size=4) +
      geom_point(data=centroids, aes(x=PC1,y=PC2, fill=response,color=response), pch=21, size=2) +
      geom_segment(aes(x=PC1.centroid, y=PC2.centroid, xend=PC1, yend=PC2, color=response), alpha=0.8) +
      scale_fill_manual(values=color) +
      scale_colour_manual(values=color) +
      xlab(paste("PC Axis 1 (", round(pc$sdev[1], 2), "%)", sep="")) +
      ylab(paste("PC Axis 2 (", round(pc$sdev[2], 2), "%)", sep="")) +
      theme_bw() +
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(), 
            plot.title = element_text(size=14,colour="black"),
            axis.text=element_text(size=14,colour="black"),text=element_text(size=14,colour="black"),
            aspect.ratio=1) +
      guides(fill = guide_legend(override.aes=list(shape=21)))

ggsave(pc1,file="../analysis/Graph/SFig6.pdf", width=6, height=4)

```

# SFig7

```{r}
group = read.csv("../analysis/A01.1-add-meta/non-melanoma-cohort-sample_10_10.csv",check.names = F)

group = group[order(group$days.sample.collect),]
group = group[order(match(group$patient_rename,unique(group$patient_rename))),]
group=group[group$clinical.response %in% c("Responder","Nonresponder"),]
group = group[order(match(group$clinical.response,c("Responder","Nonresponder"))),]
group = group[order(match(group$Tumor,unique(group$Tumor))),]


ID = unique(group$patient_rename)
rownames(group)=group$sample_id

first_sample = NULL
for(i in ID){
  tmp = group[group$patient_rename == i,]
  tmp = tmp[tmp$days.sample.collect == min(tmp$days.sample.collect),]
  first_sample = rbind(first_sample,tmp)
}

first_sample = as.data.frame(first_sample[first_sample$days.sample.collect < 180,])


first_sample = first_sample[first_sample$Tumor == "SCC",]
dat=read.csv("../analysis/A01.1-add-meta/jhmi-sears-non-melanoma.picrust2.pw.txt",sep="\t",row.names = 1,check.names = F)
differential = read.csv("../analysis/differential_analysis/combined/SCC/picrust2.pw/differential.txt",sep="\t",row.names = 1,check.names = F)
differential = na.omit(differential)
differential =differential[order(differential$log2_FC),]

description = read.csv("../analysis/A01.1-add-meta/picrust2_pw_description.txt",sep="\t",check.names = F,header=F)
rownames(description) = gsub("-","_",description$V1)
description = description[rownames(differential),]

dat = dat[,rownames(differential)]
colnames(dat) = paste(description$V1,description$V2,sep=": ")
  
first_sample = first_sample[order(first_sample$patient_rename),]
first_sample = first_sample[order(match(first_sample$clinical.response,c("Responder","Nonresponder"))),]
dat = dat[rownames(first_sample),]
rownames(dat) = first_sample$patient_rename
colnames(dat) = gsub('.c_.+.f','.f',colnames(dat))
colnames(dat) =  gsub('k_Bacteria.','',colnames(dat))
pw = dat
  

### pathway
plotPath = function(pathway_result){
  colnames(pathway_result) = c("pathway", "Total.Cmpd","Hits" , "Raw.p","-log10(p)" ,"Holm.adjust","FDR" ,"Impact" )
  plot_pathway = ggplot(pathway_result,aes(x=Impact, y=`-log10(p)`))+geom_point(aes(color=`-log10(p)`,size=Impact))+
  scale_colour_gradient(limits=c(0, round(max(pathway_result$`-log10(p)`),0)), low="red",high = "yellow") +
  geom_text_repel(data=subset(pathway_result, `-log10(p)` > 1 & Impact > 0),aes(Impact,`-log10(p)`,label=pathway),hjust=-0.2,vjust=-1)+ggtitle(" ")+
  theme_bw()+ylab("-log10(pvalue)")+theme(
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      plot.title =element_text(size=12,colour="black",hjust = 0.5),
      axis.title = element_text(size=12,colour="black"))
}

pathway_result= read.csv("../analysis/differential_analysis/metabolite/Pathway_analysis/result/pathway_results.csv")
pathway_dotplot_all = plotPath(pathway_result)


##### boxplot
boxplot <- function(name_map,input){
  name_map = name_map[name_map$Pathway !="",]
  input = input[,c("group",name_map$Query)]
 range_value = NULL
  for(i in 2:ncol(input)){
    range_value=c(range_value,list(c(range(input[,i])[1],range(input[,i])[2]*1.3)))
  }
plot = melt(input)
colnames(plot) = c("response","variable","value")
plot$response = factor(plot$response,levels = c("Responder","Nonresponder"))
a = ggplot(plot, aes(x =response, y =value ,fill=response))+
  geom_boxplot(width=0.4) +# geom_point()+
  scale_fill_manual(values=c("Nonresponder"="#3E4A7B","Responder" ="#A94643"))+ scale_colour_manual(values=c("Nonresponder"="#3E4A7B","Responder" ="#A94643"))+ 
  # statistical analysis
  stat_compare_means(comparisons =list(c("Nonresponder","Responder")),method = 't.test',size=4)+
  theme_bw()+xlab("")+ylab("")+ggtitle(" ")+scale_y_continuous(expand = expansion(mult = c(0, 0.1)))+
  facet_wrap(~variable, scales = "free",ncol=5)+
theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
      axis.text=element_text(size=12,colour="black"),text=element_text(size=12,colour="black"),
      plot.title =element_text(size=12,colour="black",hjust = 0.5),
      axis.title = element_text(size=12,colour="black"),axis.text.x = element_blank(),axis.ticks.x = element_blank())
return(a)
}


### correlation
dat = read.csv("../analysis/differential_analysis/combined/SCC/differential_genus_species.csv",row.names = 1)
dat = as.data.frame(t(dat))
first_sample = first_sample[order(first_sample$patient_rename),]
first_sample = first_sample[order(match(first_sample$clinical.response,c("Responder","Nonresponder"))),]
genus = dat[first_sample$patient_rename,]
pw_genus =as.data.frame(cbind(pw[first_sample$patient_rename,],genus)) 
colnames(pw_genus) =gsub("\\:.*", "", colnames(pw_genus))


correlation_plot = function(name_map,metabolite_data){
  name_map=name_map[name_map$Pathway != "",]
metabolite_data=metabolite_data[,name_map$Query]
metabolite_data=metabolite_data[first_sample$sample_id,]
rownames(metabolite_data) = first_sample$patient_rename


ct <- corr.test(metabolite_data,pw_genus,
                  method="spearman",
                  adjust="BH",
                  alpha =0.05) 
pvalue<-ct$p
p=pvalue
p <- pvalue[apply(pvalue,1,min,na.rm=T)<0.05,]
p <- p[,apply(p,2,min,na.rm=T)<0.05]
p = as.data.frame(p)
plot = ct$r
plot= plot[rownames(p),]
plot = plot[,colnames(p)]

###pheatmap
mycol<-c(colorRampPalette(c('blue','white'))(9),
         colorRampPalette(c('white','white'))(3),
         colorRampPalette(c('white','red'))(9))
bk<-seq(-1,1,by=0.1)

label<-matrix("", nrow=nrow(p), ncol=ncol(p))
label[which(p<0.05)]<-"*"
label[which(p<0.01)]<-"**"
label[which(p<0.001)]<-"***"
mycol<-c(colorRampPalette(c('blue','white'))(9),
         colorRampPalette(c('white','white'))(3),
         colorRampPalette(c('white','red'))(9))

pheatmap(plot,cellwidth = 15,cellheight = 15,cluster_rows = T,
         cluster_cols=F,display_numbers = label,angle_col = 45,number_color = "white",
         color=mycol,legend_breaks = seq(-1,1,by=0.2),gaps_col = c(15,15),
         breaks=bk)->y
C<-plot_grid(y$gtable)
return(C)
}

name_map = read.csv("../analysis/differential_analysis/metabolite/Pathway_analysis/result/name_map.csv")
input = read.csv("../analysis/differential_analysis/metabolite/Pathway_analysis/result/input_pathway_diff_metabo.csv",row.names = 1,check.names = F)
boxplot_all = boxplot(name_map,input)

name_map = read.csv("../analysis/differential_analysis/metabolite/Pathway_analysis/result/name_map.csv")
metabolite_data = read.csv("../analysis/differential_analysis/metabolite/Pathway_analysis/result/input_pathway_diff_metabo.csv",row.names = 1,check.names = F)
correlation_all = correlation_plot(name_map,metabolite_data)


all = ggarrange( pathway_dotplot_all, boxplot_all,correlation_all,nrow = 3,heights  =c(0.5,0.8,0.5),labels=c("A","B","C"))
ggsave(all,file="../analysis/Graph/SFig7.pdf", width=14, height=17)


```

